# Numpy Overview

**This tutorial gives a quick overview of the numpy arrays and its features**<br>
> - **Importing numpy library**<br>
> - **Creating arrays and initializing**<br>
> - **Reading arrays from files**<br>
> - **Special initializing functions**<br>
> - **Slicing and indexing**<br>
> - **reshaping arrays**<br>
> - **Numpy Maths**<br>
> - **Combining arrays**<br>
> - **Basic algebraic operations using numpy arrays**<br>
> - **Solving linear equations**<br>
> - **Matix inversions**<br>
> - **Calculating eigen vectors**<br>

# Importing numpy library

In [1]:
import numpy as np     #importing a library
from numpy import random as rd #importing a specific sub-module from the library

In [2]:
from numpy import *  #allows to use the submodules/ functiosn w/o prefix but slows down the systme and not a common practice

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

- All numerical and mathematical functions
    - logs, arithematic calc
    - matrix operations
    - Stats functions
    - trignometric
- Pandas makes use of numpy stats functions (stats measurements, stats tests) through inheritance(internally)
- To genearte some prob distributions, we use numpy (numpy.random.xxxxx())
- First - to know numpy ndarray
- Second - numy.random
- Next : some helpper arithematic function

## Creating one dimensional numpy arrays and initializing

In [4]:
## Create one dimensional array
a1=[23,44,33,66,77,88,99,12,10]
a2 = np.array([23,44,33,66,77,88,99,12,10])

print(type(a1))
print(type(a2))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
# Create a two dimensional array
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print( b )
#np.array?
#np.shape(b)

[[1 2 3]
 [4 5 6]]


In [12]:
b=np.ones((5,6))  # Create an array of all ones
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
c=np.full((2,2),1.0)
c

array([[1., 1.],
       [1., 1.]])

In [20]:
e = np.random.random(5)
e
#np.random.random?

In [34]:
e = np.random.random((2,2))
e

array([[0.50504484, 0.97154708],
       [0.56389766, 0.98032835]])

In [21]:
f=rd.randint(low=10,high=100,size=(4,4))
f

array([[13, 23, 97, 33],
       [77, 24, 26, 47],
       [63, 74, 24, 97],
       [43, 87, 86, 59]])

In [25]:
arr2=np.array([1,5,4,3,5,4,3,2,7,6,5,4])   # no of elements should be multiples of dim
arr3=arr2.reshape(3,4)
arr3

array([[1, 5, 4, 3],
       [5, 4, 3, 2],
       [7, 6, 5, 4]])

In [27]:
np.tile(arr3,(2,2))

array([[1, 5, 4, 3, 1, 5, 4, 3],
       [5, 4, 3, 2, 5, 4, 3, 2],
       [7, 6, 5, 4, 7, 6, 5, 4],
       [1, 5, 4, 3, 1, 5, 4, 3],
       [5, 4, 3, 2, 5, 4, 3, 2],
       [7, 6, 5, 4, 7, 6, 5, 4]])

In [28]:
np.ndarray(range(1,10))

array([[[[[[[[[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             ...,

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0.,

In [30]:
e.dtype

dtype('float64')

In [31]:
type(e)

numpy.ndarray

In [35]:
e.T

array([[0.50504484, 0.56389766],
       [0.97154708, 0.98032835]])

In [39]:
arr2.size

12

In [41]:
arr2.sum()

49

In [42]:
arr2.mean()

4.083333333333333

In [43]:
arr2.nbytes

48

In [45]:
arr3

array([[1, 5, 4, 3],
       [5, 4, 3, 2],
       [7, 6, 5, 4]])

In [46]:
arr1=np.array([[1,5,4,2],[2,1,4,7],[3,1,5,9]],dtype='int64')
print(arr1)

[[1 5 4 2]
 [2 1 4 7]
 [3 1 5 9]]


In [51]:
arr1.sort(axis=0)
arr1

array([[1, 2, 4, 5],
       [1, 2, 4, 7],
       [1, 3, 5, 9]], dtype=int64)

## Numpy Arrays - dtypes & shapes

In [58]:
a=np.ndarray([3,4])
a.ndim

2

In [54]:
# Find the type of the object
type(a)

numpy.ndarray

In [60]:
a1 = np.array([1,2,20,10])
a1

array([ 1,  2, 20, 10])

In [61]:
a1.ndim

1

In [62]:
## Find the dimension of the array
a.shape

(3, 4)

## Slicing & Indexing an array

In [63]:
f

array([[13, 23, 97, 33],
       [77, 24, 26, 47],
       [63, 74, 24, 97],
       [43, 87, 86, 59]])

In [67]:
# Rows before COMMA columns after COMMA
f[2:,:2]

array([[63, 74],
       [43, 87]])

In [68]:
# Get 1 and 2 row
f[:2,:3]

array([[13, 23, 97],
       [77, 24, 26]])

In [69]:
f[3:,1:]

array([[87, 86, 59]])

In [70]:
# Get first column
f[:,0]

array([13, 77, 63, 43])

In [71]:
f[:,0:2]

array([[13, 23],
       [77, 24],
       [63, 74],
       [43, 87]])

In [72]:
## slicing an array 
## All 
b = f[:2, 0:3]
b

array([[13, 23, 97],
       [77, 24, 26]])

In [73]:
# Get specific elements
np.array([f[0,1],f[2,2]])

array([23, 24])

In [76]:
## Boolean indexing
arr1==5

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False,  True, False]])

In [77]:
arr1==9

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [78]:
arr1[arr1==9]

array([9], dtype=int64)

In [79]:
arr1[arr1>3]

array([4, 5, 4, 7, 5, 9], dtype=int64)

In [80]:
#arr_2 = np.ndarray([range(0,10), range(10,20), range(20,30)])
arr_2 = np.array([range(0,10), range(10,20), range(20,30)])
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [81]:
arr_2[arr_2>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [82]:
arr_2.shape

(3, 10)

In [84]:
d=np.reshape(arr_2,(5,6))
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [85]:
arr_2.reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## Reshaping an array

In [88]:
k=np.reshape(f,(8,2))
k

array([[13, 23],
       [97, 33],
       [77, 24],
       [26, 47],
       [63, 74],
       [24, 97],
       [43, 87],
       [86, 59]])

In [89]:
np.reshape(arr_2, (6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## Updating an array

In [92]:
arr1

array([[1, 2, 4, 5],
       [1, 2, 4, 7],
       [1, 3, 5, 9]], dtype=int64)

In [93]:
arr1[arr1>=3]=10

In [94]:
arr1

array([[ 1,  2, 10, 10],
       [ 1,  2, 10, 10],
       [ 1, 10, 10, 10]], dtype=int64)

In [96]:
print(k)
k[7,1]=0
k

[[13 23]
 [97 33]
 [77 24]
 [26 47]
 [63 74]
 [24 97]
 [43 87]
 [86 59]]


array([[13, 23],
       [97, 33],
       [77, 24],
       [26, 47],
       [63, 74],
       [24, 97],
       [43, 87],
       [86,  0]])

In [97]:
k[5:]=0
k

array([[13, 23],
       [97, 33],
       [77, 24],
       [26, 47],
       [63, 74],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

## Combine Arrays

In [98]:
x=np.random.randint(10,size=(2,2))
y=np.random.randint(100,size=(2,2))
print(x)
print(y)

[[9 8]
 [3 3]]
[[52 74]
 [46 38]]


In [99]:
np.vstack([x,y])

array([[ 9,  8],
       [ 3,  3],
       [52, 74],
       [46, 38]])

In [100]:
np.hstack([x,y])

array([[ 9,  8, 52, 74],
       [ 3,  3, 46, 38]])

## NUMPY Maths

### Adding, subtracting, multiplying, transposing arryas

In [101]:
x = np.random.randint( 100, size = (5,5) )
y = np.random.randint( 100, size = (5,5) )
print(x)
print(y)

[[65 46 92 53  8]
 [31 24 25 87 88]
 [34 22 92 49 45]
 [53 50 38 43 10]
 [84 78 22 60  5]]
[[84 15 19 63  4]
 [17 21 28 35  9]
 [66 48 23 91 55]
 [93 87  6 46  2]
 [65 83 48 74 13]]


In [102]:
## Add two matrices x + y or np.add( x, y )
x + y

array([[149,  61, 111, 116,  12],
       [ 48,  45,  53, 122,  97],
       [100,  70, 115, 140, 100],
       [146, 137,  44,  89,  12],
       [149, 161,  70, 134,  18]])

In [103]:
np.add( x, y )

array([[149,  61, 111, 116,  12],
       [ 48,  45,  53, 122,  97],
       [100,  70, 115, 140, 100],
       [146, 137,  44,  89,  12],
       [149, 161,  70, 134,  18]])

In [104]:
# np.substract( x, y )
x - y

array([[-19,  31,  73, -10,   4],
       [ 14,   3,  -3,  52,  79],
       [-32, -26,  69, -42, -10],
       [-40, -37,  32,  -3,   8],
       [ 19,  -5, -26, -14,  -8]])

In [105]:
# np.multiply( x, y )
x * y

array([[5460,  690, 1748, 3339,   32],
       [ 527,  504,  700, 3045,  792],
       [2244, 1056, 2116, 4459, 2475],
       [4929, 4350,  228, 1978,   20],
       [5460, 6474, 1056, 4440,   65]])

In [106]:
# Matrix Transpose
x.T

array([[65, 31, 34, 53, 84],
       [46, 24, 22, 50, 78],
       [92, 25, 92, 38, 22],
       [53, 87, 49, 43, 60],
       [ 8, 88, 45, 10,  5]])

## Calculating column sums and row sums

In [107]:
x = np.random.randint( 10, size = (4,4) )
x

array([[0, 4, 9, 9],
       [7, 6, 4, 5],
       [5, 9, 1, 6],
       [6, 0, 0, 0]])

In [108]:
print(x.sum(),x.mean(),x.std())

71 4.4375 3.239767545673609


In [109]:
np.std(x,axis=0)

array([2.6925824 , 3.26917421, 3.5       , 3.24037035])

In [112]:
np.mean(x,axis=0)

array([4.5 , 4.75, 3.5 , 5.  ])

In [111]:
np.mean(x,axis=1)

array([5.5 , 5.5 , 5.25, 1.5 ])

In [113]:
x+[10,15,20,30]

array([[10, 19, 29, 39],
       [17, 21, 24, 35],
       [15, 24, 21, 36],
       [16, 15, 20, 30]])

In [114]:
l=np.array([[10,20], [20,30]])

In [115]:
l+10

array([[20, 30],
       [30, 40]])

In [116]:
x

array([[0, 4, 9, 9],
       [7, 6, 4, 5],
       [5, 9, 1, 6],
       [6, 0, 0, 0]])

In [117]:
np.std(x)

3.239767545673609

In [118]:
np.sum(x,axis=0)

array([18, 19, 14, 20])

In [119]:
np.sum(x,axis=1)

array([22, 22, 21,  6])

In [120]:
np.mean( x, axis = 0 )

array([4.5 , 4.75, 3.5 , 5.  ])

In [121]:
np.mean( x, axis = 1 )

array([5.5 , 5.5 , 5.25, 1.5 ])

## Linear Algebra.. Advanced Matrix Operation

In [122]:
from numpy import linalg
import numpy as np

# Solving a set of linear equations 
> 2x + 2y+3z = 5 <br>
> 3x + y +4z = 7 <br>
> 4x + 3y =10

In [123]:
a = np.array([[2,2,3], [3,1,4],[4,3,0]])
b = np.array([5,7,10])
x = np.linalg.solve(a, b)
x

array([ 2.30434783,  0.26086957, -0.04347826])

## Matrix Inversion

In [124]:
a = np.array([[1, 2], [3, 4]])
np.linalg.inv( a )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Numpy arange

In [125]:
list(range(0,20,0.5))  # This will not work as range function works on int value only

TypeError: 'float' object cannot be interpreted as an integer

In [126]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [127]:
list(np.arange(0,10,.5))

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5]

## Calculating an eigen value and vector for a matrix

In [128]:
m1 = np.diag((1, 2, 3))
m1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [129]:
eigval, eigvec = np.linalg.eig( m1 )

In [130]:
eigval

array([1., 2., 3.])

In [131]:
eigvec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])